FROM python:3.13-slim

RUN mkdir /opt/poetry

ENV POETRY_NO_INTERACTION=1 \
    POETRY_VIRTUALENVS_CREATE=false \
    POETRY_CACHE_DIR=/tmp/poetry_cache \
    POETRY_HOME=/opt/poetry \
    PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

ENV PATH="$POETRY_HOME/bin:${PATH}"

RUN apt -y update && apt -y install curl

RUN curl -sSL https://install.python-poetry.org | POETRY_VERSION=1.8.5 python3 -

WORKDIR /code

COPY pyproject.toml poetry.lock* ./

RUN poetry install --no-root && rm -rf $POETRY_CACHE_DIR

COPY . .

EXPOSE 8000

CMD ["poetry", "run", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]